packages:
  - packages/babel-plugin-island-path
  - packages/island-hydration
  - packages/plugin-markdown
  - packages/types
  - packages/utils
  - packages/wilson
  - sites/docs
  - sites/codepunkt.de
