packages:
  - packages/babel-plugin
  - packages/documents
  - packages/hydration
  - packages/markdown
  - packages/pages
  - packages/types
  - packages/utils
  - packages/wilson
  # - sites/docs
  - sites/codepunkt.de
