name: Test

on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/**'
      - 'tsconfig.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - 'package.json'
      - 'turbo.json'
      - '.github/workflows/pr-tests.yml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16]
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.2.2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Build packages
      run: pnpm build
    - name: Run tests
      run: pnpm test
