name: Test

on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/**'
      - 'tsconfig.json'
      - 'package-lock.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Set npm cache dir as output
        id: cache-dir
        run: echo "::set-output name=dir::$(npm get cache)"

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ${{ steps.cache-dir.outputs.dir }}
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-npm-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-${{ env.cache-name }}-
            ${{ runner.os }}-npm-
            ${{ runner.os }}-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build wilson
        env:
          NODE_ENV: production
        run: |
          npm run wilson:build

      # - name: Test
